name: Flutter CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write 

jobs:
  # name: Run Automated Test
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Step 0: Checkout repo
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     # Step 1: Set up Flutter
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.35.7'
  #         channel: 'stable'
  #         cache: true

  #     # Step 2: Install dependencies
  #     - name: Install dependencies
  #       run: flutter pub get

  #     # Step 3: Run lint (analyze)
  #     - name: Run Flutter Analyze (Lint)
  #       run: flutter analyze --no-fatal-infos --no-fatal-warnings

  #     # Step 4: Run tests
  #     - name: Run Flutter Tests
  #       run: flutter test --coverage

  build:
    name: Build App
    # needs: test
    runs-on: ubuntu-latest

    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    steps:
      # Step 0: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true

      # Step 2: Increment Code Version
      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{ github.run_number }}

      # Step 3: Decode Keystore
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/keystore.jks

      # Step 4: Build APK
      - name: Build AAB
        run: flutter build appbundle --release

  release:
    name: Release Build
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Extract version from pubspec.yaml
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | cut -d '+' -f1)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "Detected version: $VERSION"

      # Step 2: Check if tag already exists
      - name: Check if tag exists
        id: check_tag
        run: |
          if git ls-remote --tags origin v${{ env.VERSION }} | grep v${{ env.VERSION }}; then
            echo "Tag exists"
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "Tag does not exist"
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # Step 3: Stop if version already released
      - name: Stop if tag exists
        if: steps.check_tag.outputs.exists == 'true'
        run: |
          echo "Version already released. Skipping."
          exit 0

      # Step 4: Create and push tag
      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      # Step 5: Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true

      # Step 6: Rename AAB
      - name: Rename AAB
        run: |
          mv build/app/outputs/bundle/release/app-release.aab \
             build/app/outputs/bundle/release/app-v${{ env.VERSION }}.aab

      # Step 7: Create GitHub Release
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: Release v${{ env.VERSION }}
          generate_release_notes: true
          files: build/app/outputs/bundle/release/app-v${{ env.VERSION }}.aab


  distribute:
    name: Distribute Release to Google Play
    needs: release
    runs-on: ubuntu-latest

    steps:
      # Step 0: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true

      # Step 2: Parse auth json file
      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > android/app/service_account.json
      
      # Step 3: Deploy to Google Play
      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: android/app/service_account.json
          packageName: com.jiro.st_lorenzo_ruiz_novena
          releaseFiles: build/app/outputs/bundle/release/app-v${{ env.VERSION }}.aab
          track: internal
          status: "draft"