name: Flutter CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Step 0: Checkout repo
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     # Step 1: Set up Flutter
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.35.7'
  #         channel: 'stable'
  #         cache: true

  #     # Step 2: Install dependencies
  #     - name: Install dependencies
  #       run: flutter pub get

  #     # Step 3: Run lint (analyze)
  #     - name: Run Flutter Analyze (Lint)
  #       run: flutter analyze --no-fatal-infos --no-fatal-warnings

  #     # Step 4: Run tests
  #     - name: Run Flutter Tests
  #       run: flutter test --coverage
          
  # build:
  #   # needs: [test]
  #   name: Generate AAB
  #   runs-on: ubuntu-latest

  #   env:
  #     STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
  #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
  #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

  #   steps:
  #     # Step 0: Checkout repo
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     # Step 1: Set up Flutter
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.35.7'
  #         channel: 'stable'
  #         cache: true

  #     # Step 2: Install dependencies
  #     - name: Install dependencies
  #       run: flutter pub get

  #     # Step 4: Decode Keystore
  #     - name: Decode Keystore
  #       run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/keystore.jks

  #     # Step 5: Build APK
  #     - name: Build AAB
  #       run: flutter build appbundle --release

  #     # Step 6: Upload APK as artifact
  #     - name: Upload AAB
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: app-release-aab
  #         path: build/app/outputs/bundle/release/app-release.aab

  distribute:
    name: Distribute bundle to Google Play
    # needs: build
    runs-on: ubuntu-latest

    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    steps:
      # Step 0: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true

      # Step 2: Increment Code Version
      - name: Version Bump
        uses: chkfung/android-version-actions@v1.2.3
        with:
          gradlePath: android/app/build.gradle
          versionCode: ${{ github.run_number }}

      # Step 3: Decode Keystore
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/keystore.jks

      # Step 4: Build APK
      - name: Build AAB
        run: flutter build appbundle --release

      # Step 5: Parse auth json file
      - name: Setup Autorization with Google Play Store
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > android/app/service_account.json
      
      # Step 6: Deploy to Google Play
      - name: Deploy bundle to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: android/app/service_account.json
          packageName: com.jiro.st_lorenzo_ruiz_novena
          releaseFiles: build/app/outputs/bundle/release/app-release.aab
          track: internal
          status: "draft"