name: Flutter CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: write 

jobs:
  # test:
      # name: Run Automated Test
  #   runs-on: ubuntu-latest

  #   steps:
  #     # Step 0: Checkout repo
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     # Step 1: Set up Flutter
  #     - name: Set up Flutter
  #       uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.35.7'
  #         channel: 'stable'
  #         cache: true

  #     # Step 2: Install dependencies
  #     - name: Install dependencies
  #       run: flutter pub get

  #     # Step 3: Run lint (analyze)
  #     - name: Run Flutter Analyze (Lint)
  #       run: flutter analyze --no-fatal-infos --no-fatal-warnings

  #     # Step 4: Run tests
  #     - name: Run Flutter Tests
  #       run: flutter test --coverage

  release:
    name: Upload Release
    # needs: test
    runs-on: ubuntu-latest

    env:
      STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}

    steps:
      # Step 0: Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 1: Extract version
      - name: Extract version
        id: get_version
        run: |
          VERSION=$(grep '^version:' pubspec.yaml | sed 's/version: //' | cut -d '+' -f1)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # Step 2: Stop if tag already exists
      - name: Check if tag exists
        id: check_tag
        run: |
          if git ls-remote --tags origin v${{ steps.get_version.outputs.version }} | grep v${{ steps.get_version.outputs.version }}; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      # Step 3: Tag Checker
      - name: Stop if already released
        if: steps.check_tag.outputs.exists == 'true'
        run: |
          echo "Version already released. Skipping."
          exit 0

      # Step 4: Create tag
      - name: Create tag
        run: |
          git config user.name "jiro.octavo"
          git config user.email "jiro.octavo@gmail.com"
          git tag v${{ steps.get_version.outputs.version }}
          git push origin v${{ steps.get_version.outputs.version }}

      # Step 5: Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.7'
          channel: 'stable'
          cache: true

      # Step 6: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 7: Decode keystore
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE }}" | base64 --decode > android/app/keystore.jks

      # Step 8: Build AAB
      - name: Build AAB
        run: flutter build appbundle --release

      # Step 9: Rename AAB
      - name: Rename AAB
        run: |
          mv build/app/outputs/bundle/release/app-release.aab \
             build/app/outputs/bundle/release/app-v${{ steps.get_version.outputs.version }}.aab

      # Step 10: Create GitHub Release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: Release v${{ steps.get_version.outputs.version }}
          generate_release_notes: true
          files: build/app/outputs/bundle/release/app-v${{ steps.get_version.outputs.version }}.aab
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Step 11: Parse auth json file
      - name: Setup Authorization with Google Play Store
        run: echo '${{ secrets.PLAY_AUTH_JSON }}' > android/app/service_account.json

      # Step 12: Upload to Google Play
      - name: Upload to Google Play
        uses: r0adkll/upload-google-play@v1.1.3
        with:
          serviceAccountJson: android/app/service_account.json
          packageName: com.jiro.st_lorenzo_ruiz_novena
          releaseFiles: build/app/outputs/bundle/release/app-v${{ steps.get_version.outputs.version }}.aab
          track: internal
          status: draft